spring:
  application:
    name: regist-web-order
  redis:
    host: 139.224.56.81
    port: 6371
    password: 123456
    jedis:
      pool:
        max-active: 20
server:
  port: 7776

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
